[package]
name = "t2f"
version = "0.1.0"
authors = ["Philipp Muens <raute1337@gmx.de>"]

[dependencies]
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.22"
chase = "0.1.8"
regex = "1.0.1"
crossbeam = "0.3.2"
hyper = "0.12.6"
hyper-tls = "0.2.0"
futures = "0.1.23"
tokio = "0.1.7"
